on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.11.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.9.1"
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm -w lint

      - name: Build
        run: pnpm -w build
